import React,{useState}from"react";import{motion,useScroll,useSpring}from"framer-motion";import{ArrowUpRight,BriefcaseBusiness,ChevronDown,Download,ExternalLink,GraduationCap,Mail,MapPin,Menu,Network,PanelTop,Phone,Send,ServerCog,Sparkles,X}from"lucide-react";

const experiences=[
{period:"Present",role:"ERP Business Analyst",company:"Nexus Incorporation Pvt. Ltd.",type:"Odoo / ERP",text:"Working across business analysis and Odoo functional consulting — translating operational requirements into practical ERP workflows, documentation and implementation plans.",tags:["Odoo","Business Analysis","BRD","Client Consulting"]},
{period:"Previous",role:"Accountant",company:"Institute of Cultural Affairs (ICA) Nepal",type:"Finance & Accounting",text:"Built hands-on experience in accounting, financial operations, reporting, reconciliation and tax-related processes — the foundation that now informs my ERP work.",tags:["Accounting","Reporting","Reconciliation","Tax"]},
];

const capabilities=[
["01","ERP Business Analysis","Turning business problems into structured requirements, workflows and functional solutions.","BRD","Process Mapping","Gap Analysis"],
["02","Odoo Functional Consulting","Understanding and configuring business flows across core Odoo modules and translating them for users.","Purchase","Inventory","Accounting"],
["03","Finance & Accounting","A finance-first understanding of transactions, controls, reporting and the real-world impact of ERP decisions.","VAT / TDS","Reconciliation","Reporting"],
["04","Supply Chain & Operations","Mapping sourcing, logistics, inventory and manufacturing processes into connected ERP workflows.","Sourcing","Logistics","Manufacturing"]
];

const projects=[
{n:"01",title:"Supply Chain & Logistics Transformation",desc:"A functional approach to connecting sourcing, purchasing, inventory and logistics into a clear Odoo workflow.",stack:["Odoo","Supply Chain","BRD"]},
{n:"02",title:"Accounting & Nepal Tax Workflows",desc:"Functional analysis of accounting processes including VAT, TDS, reporting and transaction flows inside Odoo.",stack:["Accounting","VAT","TDS"]},
{n:"03",title:"Quality Control Workflow",desc:"Designing a practical QC journey from receipt and quality checks through notifications, activities and follow-up.",stack:["Quality","Inventory","Workflow"]},
{n:"04",title:"Manufacturing & Batch Operations",desc:"Functional requirements for raw materials, batches, finished goods, manufacturing and production reporting.",stack:["MRP","Batch","Reporting"]}
];

function Reveal({children,delay=0,className=""}){return <motion.div className={className} initial={{opacity:0,y:28}} whileInView={{opacity:1,y:0}} viewport={{once:true,amount:.15}} transition={{duration:.7,delay,ease:[.22,1,.36,1]}}>{children}</motion.div>}

export default function App(){
 const[menu,setMenu]=useState(false);const{scrollYProgress}=useScroll();const scaleX=useSpring(scrollYProgress,{stiffness:100,damping:30});
 const nav=(id)=>{document.getElementById(id)?.scrollIntoView({behavior:"smooth"});setMenu(false)};
 return <div className="site"><motion.div className="progress" style={{scaleX}}/><div className="noise"/><div className="orb orb1"/><div className="orb orb2"/>
 <header><a className="brand" href="#home" onClick={()=>nav("home")}><span>SB</span><strong>Susant<span>.</span></strong></a><nav className={menu?"open":""}>{["about","experience","expertise","work","contact"].map(x=><button key={x} onClick={()=>nav(x)}>{x}</button>)}<a className="nav-cta" href="mailto:susant.basnet@gmail.com">Let's talk <ArrowUpRight size={15}/></a></nav><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
 <main id="home">
 <section className="hero wrap">
   <div className="hero-copy"><div className="eyebrow"><i/> ERP BUSINESS ANALYST · ODOO</div><h1>I turn <em>business complexity</em> into systems that work.</h1><p className="lead">I'm <b>Susant Basnet</b>, an ERP Business Analyst with a foundation in finance and accounting, now focused on Odoo and business process transformation.</p><div className="actions"><button className="primary" onClick={()=>nav("work")}>Explore my work <ArrowUpRight size={17}/></button><button className="ghost" onClick={()=>nav("contact")}>Get in touch</button></div></div>
   <div className="hero-visual"><div className="portrait"><div className="portrait-grid"/><div className="initials">SB</div><div className="status"><span/>Available for meaningful ERP challenges</div></div><div className="float-card fc1"><ServerCog/><div><small>Current focus</small><strong>Odoo ERP</strong></div></div><div className="float-card fc2"><span className="mini-dot"/>Finance → ERP</div></div>
 </section>
 <div className="ticker"><div>ERP BUSINESS ANALYSIS <span>✦</span> ODOO FUNCTIONAL CONSULTING <span>✦</span> FINANCE & ACCOUNTING <span>✦</span> BUSINESS PROCESS DESIGN <span>✦</span> ERP BUSINESS ANALYSIS <span>✦</span></div></div>
 <section id="about" className="section wrap"><Reveal><div className="section-kicker">01 / ABOUT</div><div className="about-grid"><h2>Finance taught me the numbers. <em>ERP taught me the system.</em></h2><div><p className="big-copy">My career sits at the intersection of <b>finance, business processes and technology.</b> I started in accounting, where accuracy and controls matter. Today, I use that perspective to understand how organizations actually work and turn those needs into Odoo ERP solutions.</p><p>From requirement gathering and BRDs to workflow design, configuration discussions and user-facing problem solving, I enjoy being the bridge between people, processes and software.</p><button className="text-link" onClick={()=>nav("experience")}>See my journey <ArrowUpRight size={16}/></button></div></div></Reveal></section>
 <section id="experience" className="section dark"><div className="wrap"><Reveal><div className="section-kicker">02 / EXPERIENCE</div><h2 className="section-title">A career built around <em>how work gets done.</em></h2></Reveal><div className="timeline">{experiences.map((e,i)=><Reveal key={e.role} delay={i*.1}><article className="timeline-item"><div className="time">{e.period}</div><div className="line"><span/></div><div className="experience-card"><div className="role-head"><div><div className="type">{e.type}</div><h3>{e.role}</h3><h4>{e.company}</h4></div><BriefcaseBusiness size={25}/></div><p>{e.text}</p><div className="tags">{e.tags.map(t=><span key={t}>{t}</span>)}</div></div></article></Reveal>)}</div></div></section>
 <section id="expertise" className="section wrap"><Reveal><div className="section-kicker">03 / EXPERTISE</div><div className="split-head"><h2 className="section-title">What I bring to an <em>ERP team.</em></h2><p>Not just module knowledge. A business-first mindset shaped by accounting experience and hands-on ERP analysis.</p></div></Reveal><div className="cap-grid">{capabilities.map((c,i)=><Reveal key={c[1]} delay={i*.06}><article className="cap-card"><span>{c[0]}</span><Network size={23}/><h3>{c[1]}</h3><p>{c[2]}</p><div className="tags">{c.slice(3).map(t=><span key={t}>{t}</span>)}</div></article></Reveal>)}</div></section>
 <section id="work" className="section work-section"><div className="wrap"><Reveal><div className="section-kicker">04 / SELECTED WORK</div><div className="split-head"><h2 className="section-title">Problems I like <em>solving.</em></h2><p>Professional work presented as functional case studies — focused on the problem, process and ERP thinking rather than flashy screenshots.</p></div></Reveal><div className="project-list">{projects.map((p,i)=><Reveal key={p.title} delay={i*.06}><article className="project"><div className="project-number">{p.n}</div><div><h3>{p.title}</h3><p>{p.desc}</p><div className="tags">{p.stack.map(s=><span key={s}>{s}</span>)}</div></div><ArrowUpRight className="project-arrow"/></article></Reveal>)}</div></div></section>
 <section className="quote"><div className="wrap"><Reveal><Sparkles/><blockquote>“Good ERP is not about making people fit the software. It is about understanding the business well enough to make the system support the way it should work.”</blockquote><span>— SUSANT BASNET / ERP BUSINESS ANALYST</span></Reveal></div></section>
 <section id="contact" className="section contact wrap"><Reveal><div className="section-kicker">05 / CONTACT</div><div className="contact-grid"><div><h2>Let's build something <em>useful.</em></h2><p>Whether you're looking for an ERP analyst, Odoo functional consultant, or someone who can bridge finance and technology, I'd be happy to connect.</p></div><div className="contact-links"><a href="mailto:susant.basnet@gmail.com"><Mail/><div><small>Email</small><strong>susant.basnet@gmail.com</strong></div><ArrowUpRight/></a><a href="https://github.com/basnetsusant" target="_blank" rel="noreferrer"><ExternalLink/><div><small>GitHub</small><strong>github.com/basnetsusant</strong></div><ArrowUpRight/></a><div className="contact-location"><MapPin/><div><small>Based in</small><strong>Kathmandu, Nepal</strong></div></div></div></div></Reveal></section>
 </main><footer className="wrap"><span>© {new Date().getFullYear()} Susant Basnet</span><span>ERP · ODOO · BUSINESS ANALYSIS</span><button onClick={()=>nav("home")}>Back to top ↑</button></footer>
 </div>
}